Web/Areas/Admission/Controllers/CounsellerController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using DocumentFormat.OpenXml.Drawing;
using iText.Html2pdf;
using iText.Kernel.Pdf;
using iText.Layout;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OdmErp.ApplicationCore.Entities;
using OdmErp.ApplicationCore.Entities.AdmissionAggregate;
using OdmErp.ApplicationCore.Interfaces;
using OdmErp.ApplicationCore.Query;
using OdmErp.Infrastructure.DTO;
using OdmErp.Infrastructure.RepositoryImpl.AdmissionRepo;
using OdmErp.Web.Areas.Admission.Models;
using OdmErp.Web.Areas.Support.Models;
using OdmErp.Web.BillDesk;
using OdmErp.Web.LeadSquared;
using OdmErp.Web.Models;
using Web.Controllers;

using static OdmErp.Web.LeadSquared.LeadManage;

using OdmErp.Web.Areas.Admission.Constants;
using RestSharp;
using RestSharp.Serialization.Json;
using OdmErp.Web.SendInBlue;

namespace OdmErp.Web.Areas.Admission.Controllers
{
    [Area("Admission")]
    public class CounsellerController : AppController
    {
        const string ImgAnswerUrl = "answerVal";
        public AdmissionSqlQuery sqlQuery;       
        public IAdmissionExamDateAssignRepository admissionExamDateAssignRepository;
        public IAdmissionStandardExamRepository admissionStandardExamRepository;
        public IAdmissionPersonalInterviewAssignRepository admissionPersonalInterviewAssignRepository;
        public IEmployeeRepository employeeRepository;
        public IAdmissionDocumentRepository admissionDocumentRepository;
        public IAdmissionDocumentVerificationAssignRepository admissionDocumentVerificationAssignRepository;
        public IAdmissionStudentDocumentRepository admissionStudentDocumentRepository;
        public IDocumentSubTypeRepository documentSubTypeRepository;
        public IDocumentTypeRepository documentTypeRepository;
        public IPaymentType paymentType;
        public AdmissionStudentCommonMethod admissionStudentCommonMethod;
        public IBoardStandardRepository boardStandardRepository;
        public IAdmissionExamDateAssignRepository admissionExamDateAssign;
        public IAdmissionStudentExamRepository admissionStudentExamRepository;
        public IAdmissionStandardExamResultDateRepository admissionStandardExamResultDateRepository;
        public IAdmissionRepository admissionRepository;
        public IAcademicSessionRepository academicSessionRepository;
        public IAcademicStandardRepository academicStandardRepository;
        public IAcademicStandardWingRepository academicStandardWingRepository;
        public IOrganizationRepository organizationRepository;
        public IOrganizationAcademicRepository organizationAcademicRepository;
        public IBoardRepository boardRepository;
        public IAdmissionStudentContactRepository admissionStudentContactRepository;
        public IStandardRepository standardRepository;
        public IWingRepository wingRepository;
        public IBoardStandardWingRepository boardStandardWingRepository;
        public IAdmissionStudentRepository admissionStudentRepository;
        public IAdmissionStudentAcademicRepository admissionStudentAcademicRepository;
        public IAdmissionStudentStandardRepository admissionStudentStandardRepository;
        public IAdmissionFormPaymentRepository admissionFormPaymentRepository;
        public IAdmissionStudentCounselorRepository admissionStudentCounsellorRepository;
        public IAdmissionCounsellorRepository admissionCounsellorRepository;
        public IAdmissionPersonalInterviewAssignRepository admissionPersonalInterviewAssign;
        public IAdmissionDocumentAssignRepository admissionDocumentAssignRepository;
        public ICounsellorStatusRepository counsellorStatusRepository;
        public IAdmissionInterViewerRepository admissionInterViewerRepository;
        public IAdmissionVerifierRepository admissionVerifierRepository;
        public IAdmitcardDetailsRepository admitcardDetailsRepository;
        public IAdmitcardInstructionsRepository admitcardInstructionsRepository;
        public IAdmitcardVenueAddressRepository admitcardVenueAddressRepository;
        public IAdmitcardVenueRepository admitcardVenueRepository;
        public CommonMethods commonMethods;
        public AdmissionSmsnMails Emailsend;
        public IAdmissionFeeRepository admissionFeeRepository;
        public IHostingEnvironment hostingEnv;
        public smssend smssend;
        public StudentAdmissionMethod studentAdmissionMethod;
        public PaymentManager pManger;
        public AdmissionStudentCommonMethod amissionStudentCommonMethod;
        public SendInBlueEmailManager senndInBlue;


        public CounsellerController(IAdmissionStudentDocumentRepository admissionStudentDocumentRepo,
            IDocumentTypeRepository documentTypeRepo, IDocumentSubTypeRepository documentSubTypeRepo,
            IAdmissionDocumentRepository admissionDocumentRepo,
            CommonMethods commonMethods,smssend smssend, AdmissionSmsnMails Emailsend,IHostingEnvironment hostingEnv,
           IAdmissionStudentContactRepository admissionStudentContactRepository,
            IAdmissionFeeRepository admissionFeeRepository,
            PaymentManager pManger,
           
        IAdmissionDocumentVerificationAssignRepository admissionDocumentVerificationAssignRepo,
            IEmployeeRepository employeeRepo,AdmissionStudentCommonMethod admissionStudentCommonMethod,
            IAdmissionExamDateAssignRepository admissionExamDateAssignRepo,
            IAdmissionStandardExamRepository admissionStandardExamRepo, AdmissionSqlQuery sqlQ, IAdmissionDocumentAssignRepository adsRepo,
            IAcademicSessionRepository asrepo, IStandardRepository srepo, IBoardRepository brpo, IWingRepository wpo,
            IOrganizationAcademicRepository oarepo,IOrganizationRepository orepo, IAcademicStandardWingRepository aswrepo,
            IAcademicStandardRepository astdrepo, IAdmissionRepository admrepo, IBoardStandardRepository bostdrepo,
             IBoardStandardWingRepository boardStandardWingRepository,
              IAdmissionStudentRepository admStdrepo, IAdmissionStudentAcademicRepository admStdAcdrepo,
             IAdmissionStudentStandardRepository admStdStadrepo, IAdmissionFormPaymentRepository admFormParEpo,
             IPaymentType paty, IBoardStandardRepository boardStandardRepository, IAcademicStandardSettingsRepository academicStandardSettingsRepository,
         IAdmissionExamDateAssignRepository admissionExamDateAssign,IAdmissionStudentExamRepository admissionStudentExamRepository, IAdmissionStandardExamResultDateRepository admissionStandardExamResultDateRepository,
         IAdmissionPersonalInterviewAssignRepository apiasign, IAdmissionStudentCounselorRepository admissionStudentCounsellorRepository,
         IAdmissionCounsellorRepository admissionCounsellorRepository, ICounsellorStatusRepository counsellorStatusRepo,
         IAdmissionPersonalInterviewAssignRepository admissionPersonalInterviewAssignRepository, IAdmissionInterViewerRepository admissionInterViewerRepository, 
         IAdmissionVerifierRepository admissionVerifierRepository, IAdmitcardDetailsRepository admitcardDetailsRepo,
         IAdmitcardInstructionsRepository admitcardInstructionsRepo, IAdmitcardVenueAddressRepository admitcardVenueAddressRepo, 
         IAdmitcardVenueRepository admitcardVenueRepo, StudentAdmissionMethod studentAdmissionMethod, AdmissionStudentCommonMethod amissionStudentCommonMethod, SendInBlueEmailManager senndInBlue
            )
        {
            this.amissionStudentCommonMethod = amissionStudentCommonMethod;
            this.senndInBlue = senndInBlue;
            this.pManger = pManger;
            this.admissionStudentContactRepository = admissionStudentContactRepository;
            this.smssend = smssend;
            this.hostingEnv = hostingEnv;
            this.admissionFeeRepository = admissionFeeRepository;
            this.commonMethods = commonMethods;
            this.admissionInterViewerRepository = admissionInterViewerRepository;
            this.admissionStudentCommonMethod = admissionStudentCommonMethod;
            this.admissionStudentCounsellorRepository = admissionStudentCounsellorRepository;
            this.admissionCounsellorRepository = admissionCounsellorRepository;
            this.admissionDocumentAssignRepository = adsRepo;
            this.admissionPersonalInterviewAssign = apiasign;
            this.admissionPersonalInterviewAssignRepository = admissionPersonalInterviewAssignRepository;
            this.boardStandardRepository = boardStandardRepository;
            this.admissionExamDateAssign = admissionExamDateAssign;
            this.admissionStudentExamRepository = admissionStudentExamRepository;
            this.admissionStandardExamResultDateRepository = admissionStandardExamResultDateRepository;
            paymentType = paty;
            admissionStudentStandardRepository = admStdStadrepo;
            admissionStudentAcademicRepository = admStdAcdrepo;
            admissionStudentRepository = admStdrepo;
            this.boardStandardWingRepository = boardStandardWingRepository;
            academicSessionRepository = asrepo;
            academicStandardRepository = astdrepo;
            academicStandardWingRepository = aswrepo;
            organizationRepository = orepo;
            organizationAcademicRepository = oarepo;
            boardRepository = brpo;
            standardRepository = srepo;
            wingRepository = wpo;
            admissionRepository = admrepo;
            this.boardStandardRepository = bostdrepo;
            this.admissionFormPaymentRepository = admFormParEpo;
            admissionStudentDocumentRepository = admissionStudentDocumentRepo;

Web/Areas/Admission/Views/Counseller/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@model List<OdmErp.ApplicationCore.Query.View_Student_Admission_Counseller>

<div class="row holder-breadcrumb">
    <nav class="col-12" aria-label="breadcrumb">
        <ol class="breadcrumb card-header bg-white">
            <li class="breadcrumb-item"><a class="h6 mb-0 text-info font-weight-bold">Admission</a></li>
            <li class="breadcrumb-item active h6 mb-0 text-secondary font-weight-bold" aria-current="page">Student List</li>
        </ol>
    </nav>
</div>
<div class="row">

    <div class="container-fluid">
        <div class="card  mb-4 bg-white">
            <!-- Page Heading -->
            <div class="d-sm-flex align-items-center justify-content-between mb-4 card-header bg-white">
                <h1 class="h5 mb-0 text-gray-800 font-weight-bold"> Academic Details </h1>

                <div>
                    <a asp-action="ViewStudentDetails" asp-controller="Student" asp-area="Student" asp-route-id="@ViewBag.StudentId" class="d-none d-sm-inline-block btn btn-sm btn-success text-white font-weight-normal"><i class="fas fa-undo "></i> Back To List</a>
                    @*@if (ViewBag.isnew == true)
                        {*@
                    <a asp-action="CreateOrEditStudentAcademicStandard" asp-controller="Student" asp-area="Student" asp-route-eid="@ViewBag.StudentId" class="d-none d-sm-inline-block btn btn-sm btn-success text-white font-weight-normal"><i class="fas fa-plus-circle"></i>&nbsp; Create</a>
                    @*}*@
                </div>
            </div>


            <!-- Content Row -->
            <div class="row">

                <div class="container-fluid">

                    <!-- Page Heading -->
                    <!-- DataTales Example -->
                    @*<div class="card shadow mb-4">*@
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th class="h6 mb-0 text-gray-800 font-weight-bold">Form Number</th>
                                        <th class="h6 mb-0 text-gray-800 font-weight-bold">Student Name</th>
                                        <th class="h6 mb-0 text-gray-800 font-weight-bold">Phone Number</th>
                                        <th class="h6 mb-0 text-gray-800 font-weight-bold">Session</th>
                                        <th class="h6 mb-0 text-gray-800 font-weight-bold">Board</th>
                                        <th class="h6 mb-0 text-gray-800 font-weight-bold">Standard</th>
                                        <th class="h6 mb-0 text-gray-800 font-weight-bold">Wing</th>
                                        <th class="h6 mb-0 text-gray-800 font-weight-bold">Nucleus</th>

                                        <th class="h6 mb-0 text-gray-800 font-weight-bold">Applied On</th>
                                        <th class="h6 mb-0 text-gray-800 font-weight-bold">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        foreach (var item in Model)
                                        {
                                            <tr>
                                                <td class="h6 mb-0 text-gray-800 font-weight-normal">
                                                    @(item.FormNumber)
                                                </td> 
                                                <td class="h6 mb-0 text-gray-800 font-weight-normal">
                                                    @(item.StudentName)
                                                </td>   
                                                <td class="h6 mb-0 text-gray-800 font-weight-normal">
                                                    @(item.MobileNumber)
                                                </td> 
                                                <td class="h6 mb-0 text-gray-800 font-weight-normal">
                                                    @(item.SessionName)
                                                </td>
                                                <td class="h6 mb-0 text-gray-800 font-weight-normal">
                                                    @item.BoardName
                                                </td>
                                                <td class="h6 mb-0 text-gray-800 font-weight-normal">
                                                    @item.StandardName
                                                </td>
                                                <td class="h6 mb-0 text-gray-800 font-weight-normal">
                                                    @item.WingName
                                                </td>
                                                <td class="h6 mb-0 text-gray-800 font-weight-normal">
                                                    @(item.Nucleus==true?"Yes":"No")
                                                </td>
                                            
                                                <td class="h6 mb-0 text-gray-800 font-weight-normal">
                                                    @item.InsertedDate.ToString("dd-MMM-yyyy")
                                                </td>
                                                <td class="h6 mb-0 text-gray-800 font-weight-normal">
                                                    <a asp-action="ViewStudentDetails" asp-route-id="@item.AdmissionId"><i class="fas fa-eye fa-sm text-black-50"></i>Edit</a> |
                                                    @*<a asp-action="DeleteStudentAcademicStandard" asp-route-id="@item.ID" asp-route-eid="@ViewBag.StudentId" onclick="return confirm('Are you sure you wish to delete this student Academic Details?');"><i class="fas fa-trash fa-sm text-black-50"></i>Delete</a>*@

                                                </td>
                                            </tr>
                                        }
                                    }
                                </tbody>

                            </table>
                        </div>
                    </div>
                    @*</div>*@

                </div>
                <!-- /.container-fluid -->
            </div>
        </div>
    </div>
</div>

Web/Areas/Admission/Views/Counseller/ViewStudentDetails.cshtml
@{
    ViewData["Title"] = "ViewStudentDetails";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@model OdmErp.Web.Areas.Admission.Controllers.CounsellerController.studentcounsellorcls

<div class="row holder-breadcrumb">
    <nav class="col-12" aria-label="breadcrumb">
        <ol class="breadcrumb card-header bg-white">
            <li class="breadcrumb-item"><a class="h6 mb-0 text-info font-weight-bold">Admission</a></li>
            <li class="breadcrumb-item"><a class="h6 mb-0 text-info font-weight-bold" asp-action="Index" asp-controller="Counseller" asp-area="Admission">Student List</a></li>
            <li class="breadcrumb-item active h6 mb-0 text-secondary font-weight-bold" aria-current="page">View Student Details</li>
        </ol>
    </nav>
</div>
<div class="row">
    <div class="form-group text-center">
        <img style="width:120px;height:120px;" src="/ODMImages/AdmissionDocuments/@Model.view_Student_.ProfileImage" />
    </div>
    <div class="form-group text-center">
        <h3><strong>@Model.view_Student_.StudentName</strong></h3>
        <h5><strong>Form No. :</strong>@Model.view_Student_.FormNumber</h5>
    </div>
    <div class="row">
        <div class="col-md-2">

        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-3">
                    <div class="col-md-3">
                        <strong>Applied On :</strong>
                    </div>
                    <div class="col-md-4">
                        @Model.view_Student_.InsertedDate.ToString("dd-MM-yyyy")
                    </div>
                    <strong>Session :</strong>
                </div>
                <div class="col-md-4">
                    @Model.view_Student_.SessionName
                </div>


            </div>
            <div class="clearfix" style="margin-bottom:10px;"></div>
            <div class="row">
                <div class="col-md-3">
                    <strong>Organisation :</strong>
                </div>
                <div class="col-md-4">
                    @Model.view_Student_.OrganisationName
                </div>
                <div class="col-md-3">
                    <strong>Board :</strong>
                </div>
                <div class="col-md-4">
                    @Model.view_Student_.BoardName
                </div>

            </div>
            <div class="clearfix" style="margin-bottom:10px;"></div>
            <div class="row">
                <div class="col-md-3">
                    <strong>Standard :</strong>
                </div>
                <div class="col-md-4">
                    @Model.view_Student_.StandardName
                </div>
                <div class="col-md-3">
                    <strong>Wing :</strong>
                </div>
                <div class="col-md-4">
                    @Model.view_Student_.WingName
                </div>

            </div>
        </div>
        <div class="col-md-2">

        </div>
    </div>
    <div class="clearfix" style="margin-bottom:20px;"></div>
    <div class="row">
        <div class="d-sm-flex align-items-center justify-content-between mb-4 card-header bg-white">
            <h1 class="h5 mb-0 text-gray-800 font-weight-bold"> Exam Details </h1>

            <div>
                <a onclick="openassignexam(@(Model.standardExam==null?0:Model.standardExam.ID),'@(Model.standardExam==null?"":Model.standardExam.ExamDate.Value.ToString("yyyy-MM-dd"))');" class="d-none d-sm-inline-block btn btn-sm btn-success text-white font-weight-normal"><i class="fas fa-plus "></i>@(Model.standardExam==null?"Assign Date":"Change Date")</a>
               
            </div>
        </div>

    </div>
    <div class="clearfix" style="margin-bottom:10px;"></div>
    <div class="row">
        <div class="col-md-3"><strong>Exam Date :</strong></div>
        <div class="col-md-3">@Model.standardExam.ExamDate.Value.ToString("dd-MM-yyyy")</div>
        <div class="col-md-3"><strong>Reach Time :</strong></div>
        <div class="col-md-3">@Model.standardExam.ReachTime</div>
    </div>
    <div class="clearfix" style="margin-bottom:10px;"></div>
    <div class="row">
        <div class="col-md-3"><strong>Exam Time :</strong></div>
        <div class="col-md-3">@Model.standardExam.ExamTimeDisplayName</div>
    </div>
    <div class="clearfix" style="margin-bottom:20px;"></div>
    <div class="row">
        <div class="form-group">
            <h3><strong>PI Details :</strong></h3>
        </div>
    </div>
    <div class="clearfix" style="margin-bottom:10px;"></div>
    <div class="row">
        <div class="col-md-3"><strong>Exam Date :</strong></div>
        <div class="col-md-3">@Model.examcounseller.interviewAssign.PIDate.Value.ToString("dd-MM-yyyy")</div>
        <div class="col-md-3"><strong>Exam Time :</strong></div>
        <div class="col-md-3">@(Model.examcounseller.interviewAssign.PITime)</div>
    </div>
    <div class="clearfix" style="margin-bottom:10px;"></div>
    <div class="row">
        <div class="col-md-3"><strong>Counseller Name :</strong></div>
        <div class="col-md-3">@Model.examcounseller.AssignedCounselorName</div>
        <div class="col-md-3"><strong>Taken By :</strong></div>
        <div class="col-md-3">@Model.examcounseller.EmployeeName</div>
    </div>
    <div class="clearfix" style="margin-bottom:10px;"></div>
    <div class="row">
        <div class="col-md-3"><strong>Appeared Date :</strong></div>
        <div class="col-md-3">@Model.examcounseller.interviewAssign.AppearedDateTime.Value.ToString("dd-MM-yyyy")</div>
        <div class="col-md-3"><strong>Is Appeared :</strong></div>
        <div class="col-md-3">@(Model.examcounseller.interviewAssign.IsAppeared==true?"Yes":"No")</div>
    </div>
    <div class="clearfix" style="margin-bottom:10px;"></div>
    <div class="row">
        <div class="col-md-3"><strong>Is Qualified :</strong></div>
        <div class="col-md-3">@(Model.examcounseller.interviewAssign.IsQualified==true?"Yes":"No")</div>
    </div>
    <div class="clearfix" style="margin-bottom:20px;"></div>
    <div class="row">
        <div class="form-group">
            <h3><strong>Document Verification Details :</strong></h3>
        </div>
    </div>
    <div class="clearfix" style="margin-bottom:10px;"></div>
    <div class="row">
        <div class="col-md-3"><strong>Exam Date :</strong></div>
        <div class="col-md-3">@Model.verificationAssign.verificationAssign.AppearedDateTime.Value.ToString("dd-MM-yyyy")</div>
        <div class="col-md-3"><strong>Assigned By :</strong></div>
        <div class="col-md-3">@(Model.verificationAssign.AssignedCounselorName)</div>
    </div>
    <div class="clearfix" style="margin-bottom:10px;"></div>
    <div class="row">
        <div class="col-md-3"><strong>Taken By :</strong></div>
        <div class="col-md-3">@(Model.verificationAssign.EmployeeName)</div>
        <div class="col-md-3"><strong>Is Appeared :</strong></div>
        <div class="col-md-3">@(Model.verificationAssign.verificationAssign.IsAppeared==true?"Yes":"No")</div>

    </div>
    <div class="clearfix" style="margin-bottom:10px;"></div>
    <div class="row">
        <div class="col-md-3"><strong>Is Qualified :</strong></div>
        <div class="col-md-3">@(Model.verificationAssign.verificationAssign.IsQualified==true?"Yes":"No")</div>
        <div class="col-md-3"><strong>Verification Date &amp; Time :</strong></div>
        <div class="col-md-3">@(Model.verificationAssign.verificationAssign.VerificationDate.Value.ToString("dd-MM-yyyy")+" "+ Model.verificationAssign.verificationAssign.VerificationTime)</div>
    </div>
    <div class="clearfix" style="margin-bottom:20px;"></div>
    <div class="row">
        <div class="form-group">
            <h3><strong>Submitted Document Details :</strong></h3>
        </div>
    </div>
    <div class="clearfix" style="margin-bottom:10px;"></div>
    <div class="row">
        @foreach (var a in Model.documentscls)
        {
            <div>

            </div>
        }
    </div>
</div>
<div class="modal fade" id="AssignExamModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5>Assign Exam</h5>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">

                <form asp-action="statuschangetoverify" enctype="multipart/form-data" method="post" id="validation-form">
                    <input type="hidden" id="hdnassignexamid" name="hdnassignexamid" value="0" />
                    <div class="row">
                        <div class="col-md-4">
                            Exam Date
                        </div>
                        <div class="col-md-8">
                            <select id="txtdate" name="txtdate" class="form-control">
                                <option value="0">Select Date</option>
                            </select>  
                            <span class="text-danger" id="ValidateDate"></span>
                        </div>
                    </div>
                    <div class="clearfix" style="margin-bottom:10px;"></div>
                    <div class="form-group text-center">
                        <input type="submit" class="btn btn-primary" value="Submit Date" />
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
<script>
    function openassignexam(id,date) {
        $('#txtdate').val(date);
        $('#hdnassignexamid').val(id);
        $('#AssignExamModal').modal('show');
    }
    $(document).ready(function () {
        $("#validation-form").on("submit", function (event) {
            $('#divloader').fadeIn(300);
            event.preventDefault();
            if ($('#txtdate').val() == '') {
                $('#ValidateDate').html('Select Date');
                $('#divloader').fadeOut(300);
                return false;
            }
            var url = $(this).attr("action");
            var formData = new FormData($("#validation-form")[0]);
            $.ajax({
                url: url,
                type: "POST",
                data: formData,
                dataType: "json",
                processData: false,
                contentType: false,
                success: function (resp) {

                    $("#divloader").fadeOut(300);
                    if (resp.sts == 1) {
                        // Do something useful with the data:
                        var message = "Saved Successfully";
                        alert(message);
                        window.location.href = '/Admission/Counseller/ViewStudentDetails?id=' + resp.id;
                    }
                    else if (resp.sts == 2) {
                        // Do something useful with the data:
                        var message = "Updated Successfully";
                        alert(message);
                        window.location.href = '/Admission/Counseller/ViewStudentDetails?id=' + resp.id;
                    }
                    
                    else if (resp.sts == 0) {
                        var message = "Some Error Occured";
                        alert(message);
                        return false;
                    }
                },
                error: function (resp) {

                    $("#divloader").fadeOut(300);
                    if (resp.sts == 1) {
                        // Do something useful with the data:
                        var message = "Saved Successfully";
                        alert(message);
                        window.location.href = '/Admission/Counseller/ViewStudentDetails?id=' + resp.id;
                    }
                    else if (resp.sts == 2) {
                        // Do something useful with the data:
                        var message = "Updated Successfully";
                        alert(message);
                        window.location.href = '/Admission/Counseller/ViewStudentDetails?id=' + resp.id;
                    }
                    else if (resp.sts == 3) {
                        // Do something useful with the data:
                        var message = "School Code Already Exists";
                        alert(message);
                        return false;
                    }
                    else if (resp.sts == 0) {
                        var message = "Some Error Occured";
                        alert(message);
                        return false;
                    }
                }

            })
        })
    })
</script>